/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivosRouteImport } from './routes/ativos'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as VulnerabilidadesRouteImport } from './routes/vulnerabilidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosRoute = AtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilidadesRoute = VulnerabilidadesRouteImport.update({
  id: '/vulnerabilidades',
  path: '/vulnerabilidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/sla': typeof SlaRoute
  '/squads': typeof SquadsRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/sla': typeof SlaRoute
  '/squads': typeof SquadsRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ativos': typeof AtivosRoute
  '/sla': typeof SlaRoute
  '/squads': typeof SquadsRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ativos' | '/sla' | '/squads' | '/vulnerabilidades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ativos' | '/sla' | '/squads' | '/vulnerabilidades'
  id: '__root__' | '/' | '/ativos' | '/sla' | '/squads' | '/vulnerabilidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtivosRoute: typeof AtivosRoute
  SlaRoute: typeof SlaRoute
  SquadsRoute: typeof SquadsRoute
  VulnerabilidadesRoute: typeof VulnerabilidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos': {
      id: '/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilidades': {
      id: '/vulnerabilidades'
      path: '/vulnerabilidades'
      fullPath: '/vulnerabilidades'
      preLoaderRoute: typeof VulnerabilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtivosRoute: AtivosRoute,
  SlaRoute: SlaRoute,
  SquadsRoute: SquadsRoute,
  VulnerabilidadesRoute: VulnerabilidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
